-- MySQL Script generated by MySQL Workbench
-- 2017年10月15日 星期日 15时50分40秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema liuhecai
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema liuhecai
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `liuhecai` DEFAULT CHARACTER SET utf8 ;
USE `liuhecai` ;

-- -----------------------------------------------------
-- Table `liuhecai`.`recommend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `liuhecai`.`recommend` (
  `id` INT NOT NULL,
  `string` VARCHAR(255) NULL,
  `datetime` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `index_time` USING BTREE (`datetime` ASC)  COMMENT '时间索引')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '每日推荐六合彩的类型';


-- -----------------------------------------------------
-- Table `liuhecai`.`lottery`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `liuhecai`.`lottery` (
  `id` INT NOT NULL,
  `key1` INT UNSIGNED NULL,
  `key2` INT UNSIGNED NULL,
  `key3` INT UNSIGNED NULL,
  `key4` INT UNSIGNED NULL,
  `key5` INT UNSIGNED NULL,
  `key6` INT UNSIGNED NULL,
  `skey` INT UNSIGNED NULL,
  `datetime` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `index_time` USING BTREE (`datetime` ASC)  COMMENT '时间索引')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '开奖结果';


-- -----------------------------------------------------
-- Table `liuhecai`.`buy`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `liuhecai`.`buy` (
  `id` INT NOT NULL,
  `type` TINYINT(1) NULL COMMENT '\n1.波色  2生肖  \n3号码   4单双',
  `data` INT(3) NULL COMMENT '这里是数据\n比如\n单双是 1 2\n生肖是 1-13 十二生肖加麒麟\n颜色    1-2 红蓝\n数值    1-53',
  `time` DATETIME NULL COMMENT '购买时间',
  PRIMARY KEY (`id`),
  INDEX `index_time` USING BTREE (`time` ASC)  COMMENT '时间索引')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '购买统计表';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
